### ISSUE TITLE
[scale-ts] better error handling for enums

### ISSUE THREAD

**Issue by ryanleecode** [unstoppablejs/unstoppablejs#19]
When decoding an Enum, there should be a check on the [`idx`](https://github.com/unstoppablejs/unstoppablejs/blob/main/packages/scale-ts/src/codecs/Enum.ts#L37) such that `idx <= entries.length`. Otherwise, you get a bad error message when trying to destructure `entries[idx]` because it returns `undefined`.

Something like "Enum index exceeds Enum member size" ... basically a descriptive enough message such that I don't need to dig into the internals of `scale-ts`.

```
/home/ryan/Documents/Projects/capi2-playground/node_modules/.pnpm/scale-ts@1.3.0/node_modules/scale-ts/src/codecs/Enum.ts:39
    return {
           ^


TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at <anonymous> (/home/ryan/Documents/Projects/capi2-playground/node_modules/.pnpm/scale-ts@1.3.0/node_modules/scale-ts/src/codecs/Enum.ts:39:12)
    at <anonymous> (/home/ryan/Documents/Projects/capi2-playground/node_modules/.pnpm/scale-ts@1.3.0/node_modules/scale-ts/src/internal/toInternalBytes.ts:60:5)
Node.js v20.3.1
```

**Comment by josepot** [comment]
> When decoding an Enum, there should be a check on the [idx](https://github.com/unstoppablejs/unstoppablejs/blob/main/packages/scale-ts/src/codecs/Enum.ts#L37) such that idx <= entries.length. Otherwise, you get a bad error message when trying to destructure entries[idx] because it returns undefined.

I understand why you feel like this. However, please keep in mind that this library is very unapologetic about not dealing with input validations (for both: encoders and decoders). This is something that should be properly explained in the README, though, as I can see how this can be quite shocking. So, I will [open an issue about that](https://github.com/unstoppablejs/unstoppablejs/issues/24).
